FROM python:3.5

ADD config.py /
ADD *.py *.html /
RUN mkdir /data
ADD data /data
RUN mkdir /datasets
ADD datasets /datasets
RUN mkdir /train
ADD train /train
RUN pip3 install tqdm tensorflow spacy bottle
ENTRYPOINT ["python", "-u", "./config.py"]
EXPOSE 8080
